import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'rewear.',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    /* smooth scrolling */
    <html lang="en" style={{scrollBehavior:'smooth'}}>
      <body className={inter.className}>
      {/* added the navbar */}
      <Navbar />
      {children}
      <Footer />
      </body>
    </html>
  )
}
